/// <reference lib="dom" />
import React, { useEffect, useRef, useState } from "react";
import { buildTemplate } from "./template.js";
import { sanitizeCode } from "./sanitize.js";

export interface RenderizeProps {
  /** React code generated by the LLM. Must define a function component named App. */
  code: string;
  /** Height of the sandbox iframe. Defaults to "100%" */
  height?: string | number;
  /** Width of the sandbox iframe. Defaults to "100%" */
  width?: string | number;
  /** Custom class name for the wrapper element */
  className?: string;
  /** Custom inline styles for the wrapper element */
  style?: React.CSSProperties;
  /** Called when the sandbox encounters a runtime error */
  onError?: (error: string) => void;
}

export function Renderize({
  code,
  height = "100%",
  width = "100%",
  className,
  style,
  onError,
}: RenderizeProps) {
  const iframeRef = useRef<HTMLIFrameElement>(null);
  const [srcDoc, setSrcDoc] = useState<string | null>(null);

  useEffect(() => {
    if (!code?.trim()) return;
    setSrcDoc(buildTemplate(sanitizeCode(code)));
  }, [code]);

  // Central message handler — handles both fetch proxying and error forwarding
  useEffect(() => {
    const handler = async (event: MessageEvent) => {
      if (event.data?.source !== "renderize") return;

      // ── Fetch proxy ────────────────────────────────────────────────
      if (event.data.type === "fetch-request") {
        const { id, url, options } = event.data;

        try {
          const res = await fetch(url, {
            method: options.method,
            headers: options.headers,
            body: options.body ?? undefined,
          });

          // Serialize the response body as text — the iframe will parse it
          const body = await res.text();

          iframeRef.current?.contentWindow?.postMessage(
            {
              source: "renderize",
              type: "fetch-response",
              id,
              status: res.status,
              statusText: res.statusText,
              // Convert Headers to a plain object for structured clone
              headers: Object.fromEntries(res.headers.entries()),
              body,
            },
            "*"
          );
        } catch (err) {
          iframeRef.current?.contentWindow?.postMessage(
            {
              source: "renderize",
              type: "fetch-response",
              id,
              error: err instanceof Error ? err.message : String(err),
            },
            "*"
          );
        }
      }

      // ── Error forwarding ───────────────────────────────────────────
      if (event.data.type === "error" && onError) {
        onError(event.data.message);
      }
    };

    window.addEventListener("message", handler);
    return () => window.removeEventListener("message", handler);
  }, [onError]);

  return (
    <div
      className={className}
      style={{ width, height, overflow: "hidden", ...style }}
    >
      {srcDoc && (
        <iframe
          key={srcDoc}
          ref={iframeRef}
          srcDoc={srcDoc}
          title="Renderize Sandbox"
          sandbox="allow-scripts allow-forms allow-modals allow-popups allow-downloads"
          style={{
            width: "100%",
            height: "100%",
            border: "none",
            display: "block",
          }}
        />
      )}
    </div>
  );
}