import React, { useEffect, useRef, useState } from "react";
import { buildTemplate } from "./template.js";

export interface RenderizeProps {
  /** React code generated by the LLM. Must export a default `App` function component. */
  code: string;
  /** Height of the sandbox iframe. Defaults to "100%" */
  height?: string | number;
  /** Width of the sandbox iframe. Defaults to "100%" */
  width?: string | number;
  /** Custom class name for the wrapper element */
  className?: string;
  /** Custom inline styles for the wrapper element */
  style?: React.CSSProperties;
  /** Called when the sandbox encounters a runtime error */
  onError?: (error: string) => void;
}

export function Renderize({
  code,
  height = "100%",
  width = "100%",
  className,
  style,
  onError,
}: RenderizeProps) {
  const iframeRef = useRef<HTMLIFrameElement>(null);
  const blobUrlRef = useRef<string | null>(null);
  const [key, setKey] = useState(0);

  useEffect(() => {
    if (!code?.trim()) return;

    // Revoke previous blob URL to free memory
    if (blobUrlRef.current) {
      URL.revokeObjectURL(blobUrlRef.current);
    }

    const html = buildTemplate(code);
    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);

    blobUrlRef.current = url;

    if (iframeRef.current) {
      iframeRef.current.src = url;
    }

    // Force iframe remount when code changes to ensure clean state
    setKey((prev) => prev + 1);

    return () => {
      if (blobUrlRef.current) {
        URL.revokeObjectURL(blobUrlRef.current);
        blobUrlRef.current = null;
      }
    };
  }, [code]);

  // Forward runtime errors from the iframe to the parent
  useEffect(() => {
    const handler = (event: MessageEvent) => {
      if (
        event.data?.source === "renderize" &&
        event.data?.type === "error" &&
        onError
      ) {
        onError(event.data.message);
      }
    };
    window.addEventListener("message", handler);
    return () => window.removeEventListener("message", handler);
  }, [onError]);

  return (
    <div
      className={className}
      style={{ width, height, overflow: "hidden", ...style }}
    >
      <iframe
        key={key}
        ref={iframeRef}
        title="Renderize Sandbox"
        sandbox="allow-scripts"
        style={{
          width: "100%",
          height: "100%",
          border: "none",
          display: "block",
        }}
      />
    </div>
  );
}