/// <reference lib="dom" />
import React, { useEffect, useState } from "react";
import { buildTemplate } from "./template.js";

export interface RenderizeProps {
  /** React code generated by the LLM. Must define a function component named App. */
  code: string;
  /** Height of the sandbox iframe. Defaults to "100%" */
  height?: string | number;
  /** Width of the sandbox iframe. Defaults to "100%" */
  width?: string | number;
  /** Custom class name for the wrapper element */
  className?: string;
  /** Custom inline styles for the wrapper element */
  style?: React.CSSProperties;
  /** Called when the sandbox encounters a runtime error */
  onError?: (error: string) => void;
}

export function Renderize({
  code,
  height = "100%",
  width = "100%",
  className,
  style,
  onError,
}: RenderizeProps) {
  const [srcDoc, setSrcDoc] = useState<string | null>(null);

  useEffect(() => {
    if (!code?.trim()) return;
    // srcdoc works with sandbox="allow-scripts" — no blob URL needed,
    // no same-origin restriction, content is inlined directly
    setSrcDoc(buildTemplate(code));
  }, [code]);

  // Forward runtime errors from the iframe to the parent
  useEffect(() => {
    const handler = (event: MessageEvent) => {
      if (
        event.data?.source === "renderize" &&
        event.data?.type === "error" &&
        onError
      ) {
        onError(event.data.message);
      }
    };
    window.addEventListener("message", handler);
    return () => window.removeEventListener("message", handler);
  }, [onError]);

  return (
    <div
      className={className}
      style={{ width, height, overflow: "hidden", ...style }}
    >
      {srcDoc && (
        <iframe
          // key forces a full remount on every new render,
          // guaranteeing a clean JS context each time
          key={srcDoc}
          srcDoc={srcDoc}
          title="Renderize Sandbox"
          sandbox="allow-scripts allow-forms allow-modals allow-popups allow-downloads"
          style={{
            width: "100%",
            height: "100%",
            border: "none",
            display: "block",
          }}
        />
      )}
    </div>
  );
}